defaults:
  - architecture: transformer/nano
  - loss_function: cross_entropy
  - encoder/input_encoder: action_tokenizer
  - encoder/output_encoder: win_prob

use_wandb: true
model_version: "2.33"
description: "full_nano_run"
epochs: 1
lr: 0.0001 # 0.0001 is a good starting point
lr_decay_rate: 1
batch_size: 512
val_log_frequency: 16777216
train_log_frequency: 262144
max_val_samples: 100000
max_puzzles: 10000
device: "auto"
K: 128
M: 32
resume_from_checkpoint: null
save_checkpoint_every_n_steps: 32768
wandb_run_id: null
